### ISSUE TITLE
revpe_distcorr: the dw_scheme is changed after running the script

### ISSUE THREAD

**Issue by chunhungyeh** [MRtrix3/mrtrix3#319]
I think it was not the case before, but the current `revpe_distcorr` script on the master branch creates a different dw_scheme for the output data (i.e. the dw_schemes of the output and input image series are different). It would affect the consequential FOD estimate.

**Comment by Lestropie** [comment]
Well, that's ... not good. Is it a big rotation or subtle? One thing I did at some point was take the `bvecs/bvals` pair that the script creates for the sake of `eddy`, and re-import them into the output file; that way, if `eddy` is updated to perform gradient reorientation, that change will be reflected in the results of this script.

But my concern is that the import/export of `bvecs/bvals` files may still not be completely robust, which would be ... not good. Especially considering the heartache and effort that went into getting it right.

**Comment by jdtournier** [comment]
May or may not be related, but note there's been a few changes to the handling of the DW gradient table to handle precisely these kinds of issues - see #151 & #178 for details.

**Comment by Lestropie** [comment]
Just did a _quick_ test and the only differences I saw were due to floating-point rounding; wasn't the full script execution though. You'll have to show me whether it's a rotation, axis swapping (there is some axis stride handling in there), or b-value scaling.

**Comment by jdtournier** [comment]
Check out the commit I just pushed (ad2c774f) - fixes issues someone just reported to me in loading external DW gradient tables. This was due to a recent change to the matrix loading code (7f97a84d) to handle arbitrary separators. Unfortunately consecutive instances of the separator where interpreted as separate, leading the parser to insert additional empty fields for a gradient file that was column-aligned (and padded by spaces). It might conceivably by related to the issues here...?

**Comment by chunhungyeh** [comment]
Here is an example of my dw_scheme before and after `revpe_distcorr` (before https://github.com/MRtrix3/mrtrix3/commit/ad2c774f761f02b0d1cc70524dab39f670481316). The stride did not change after running the script (both -0,-1,+2,+3).

Before `revpe_distcorr`:
````
dw_scheme: 0,0,1,0
dw_scheme: 0,0,1,0
dw_scheme: 0.0226657,-0.10009,0.99472,2950
dw_scheme: 0.00538141,0.942767,0.333409,3000
dw_scheme: -0.527356,0.83551,0.15433,3000
dw_scheme: 0.783343,0.604666,0.144056,3000
dw_scheme: 0.0350201,-0.490589,0.870687,3000
dw_scheme: 0.381493,0.641739,0.665308,3000
dw_scheme: 0.671975,-0.700631,0.23993,3000
dw_scheme: -0.237616,-0.9666,-0.0960371,3000
dw_scheme: -0.711134,-0.557392,0.428488,3000
dw_scheme: 0.875833,-0.398805,-0.271792,3000
dw_scheme: 0,0,1,0
dw_scheme: 0.875788,-0.438367,0.202066,3000
dw_scheme: 0.772592,-0.63131,-0.0674461,3000
dw_scheme: 0.80974,0.411355,0.41846,3000
dw_scheme: 0.177001,-0.901491,0.394948,3000
dw_scheme: 0.64316,-0.252122,0.723035,3000
dw_scheme: 0.329028,0.856569,0.39753,3000
dw_scheme: 0.319778,0.0551209,0.945888,3000
dw_scheme: 0.97008,-0.00040634,0.242784,3000
dw_scheme: -0.223693,0.691639,0.686729,3000
dw_scheme: 0.455184,-0.745366,0.48707,3000
dw_scheme: 0,0,1,0
dw_scheme: 0.0862737,0.785224,0.613172,3000
dw_scheme: 0.606604,0.673899,0.421773,3000
dw_scheme: 0.414711,-0.895627,0.160831,3000
dw_scheme: 0.180094,-0.717464,0.672913,3000
dw_scheme: -0.155386,-0.896224,0.415497,3000
dw_scheme: -0.877741,-0.246547,0.410835,3000
dw_scheme: 0.977241,-0.211031,-0.0215815,3000
dw_scheme: 0.612271,0.0804045,0.786549,3000
dw_scheme: -0.674074,-0.72466,0.143149,3000
dw_scheme: -0.753376,0.324474,0.571962,3000
dw_scheme: 0,0,1,0
dw_scheme: -0.418317,-0.518092,0.746051,3000
dw_scheme: -0.986014,-0.110328,0.124916,3000
dw_scheme: -0.875061,-0.459017,0.153532,3000
dw_scheme: -0.749064,0.00476858,0.662481,3000
dw_scheme: 0.941297,0.311102,0.131057,3000
dw_scheme: 0.0412382,0.239134,0.97011,3000
dw_scheme: -0.665672,0.636665,0.38928,3000
dw_scheme: 0.328691,0.379019,0.865047,3000
dw_scheme: -0.257454,0.0905236,0.962041,3000
dw_scheme: 0.0387668,0.544959,0.837566,3000
dw_scheme: 0,0,1,0
dw_scheme: 0.836229,0.102164,0.53878,3000
dw_scheme: -0.674508,-0.324785,0.662989,3000
dw_scheme: -0.151652,-0.707647,0.690099,3000
dw_scheme: -0.503124,-0.114346,0.856616,3000
dw_scheme: 0.610004,0.398724,0.684774,3000
dw_scheme: 0.690459,-0.510524,0.512476,3000
dw_scheme: 0.856479,-0.227613,0.463289,3000
dw_scheme: -0.00504462,-0.991172,0.132485,3000
dw_scheme: -0.235213,-0.30141,0.924028,3000
dw_scheme: -0.538962,0.223171,0.812228,3000
dw_scheme: 0,0,1,0
dw_scheme: -0.514422,0.532107,0.672482,3000
dw_scheme: 0.538412,0.831646,0.135928,3000
dw_scheme: 0.293068,-0.281317,0.913768,3000
dw_scheme: 0.440628,-0.518635,0.732711,3000
dw_scheme: -0.267801,0.413367,0.870293,3000
dw_scheme: -0.394582,-0.900216,0.184163,3000
dw_scheme: -0.227817,0.968626,0.0993167,3000
dw_scheme: -0.311529,0.85763,0.40917,3000
dw_scheme: -0.91743,0.0898838,0.387612,3000
dw_scheme: 0,0,1,0
dw_scheme: -0.442842,-0.745763,0.497724,3000
````

After `revpe_distcorr`:
````
dw_scheme: 0.044931,-0.194184,0.979935,0
dw_scheme: 0.044931,-0.194184,0.979935,0
dw_scheme: 0.0224923,-0.0950752,0.995216,2950
dw_scheme: 0.00545003,-0.989579,0.14389,3000
dw_scheme: 0.530071,-0.847243,-0.0347042,3000
dw_scheme: -0.778736,-0.624576,0.0589453,3000
dw_scheme: 0.00629833,0.312018,0.950055,3000
dw_scheme: -0.354039,-0.760391,0.544484,3000
dw_scheme: -0.657422,0.637736,0.40136,3000
dw_scheme: 0.237318,0.967887,0.0829121,3000
dw_scheme: 0.732118,0.466705,0.496175,3000
dw_scheme: -0.885395,0.440128,-0.149545,3000
dw_scheme: 0.044931,-0.194184,0.979935,0
dw_scheme: -0.863884,0.386921,0.322486,3000
dw_scheme: -0.772053,0.628979,0.0912111,3000
dw_scheme: -0.791925,-0.488347,0.366567,3000
dw_scheme: -0.155103,0.80685,0.570032,3000
dw_scheme: -0.608907,0.104084,0.786383,3000
dw_scheme: -0.314606,-0.9189,0.238005,3000
dw_scheme: -0.277195,-0.239157,0.930573,3000
dw_scheme: -0.958181,-0.0510211,0.281578,3000
dw_scheme: 0.251273,-0.810833,0.528594,3000
dw_scheme: -0.429551,0.634583,0.642487,3000
dw_scheme: 0.044931,-0.194184,0.979935,0
dw_scheme: -0.0620955,-0.889718,0.452267,3000
dw_scheme: -0.590004,-0.745639,0.309705,3000
dw_scheme: -0.403115,0.845512,0.350154,3000
dw_scheme: -0.146514,0.572337,0.806823,3000
dw_scheme: 0.177846,0.799157,0.574211,3000
dw_scheme: 0.896392,0.165942,0.411029,3000
dw_scheme: -0.976284,0.206896,0.0637389,3000
dw_scheme: -0.576661,-0.234307,0.782664,3000
dw_scheme: 0.683012,0.686032,0.250708,3000
dw_scheme: 0.776877,-0.426041,0.463628,3000
dw_scheme: 0.044931,-0.194184,0.979935,0
dw_scheme: 0.453694,0.365197,0.812891,3000
dw_scheme: 0.991107,0.0883151,0.099531,3000
dw_scheme: 0.88309,0.424318,0.200268,3000
dw_scheme: 0.778045,-0.13002,0.614606,3000
dw_scheme: -0.935819,-0.334774,0.11031,3000
dw_scheme: 0.00133811,-0.423142,0.906062,3000
dw_scheme: 0.679678,-0.697198,0.227929,3000
dw_scheme: -0.291159,-0.541228,0.788859,3000
dw_scheme: 0.300018,-0.274478,0.913592,3000
dw_scheme: -0.00349602,-0.697393,0.71668,3000
dw_scheme: 0.044931,-0.194184,0.979935,0
dw_scheme: -0.811619,-0.208526,0.545703,3000
dw_scheme: 0.70504,0.19283,0.682448,3000
dw_scheme: 0.185623,0.560832,0.806853,3000
dw_scheme: 0.541604,-0.051956,0.839027,3000
dw_scheme: -0.580371,-0.526791,0.621016,3000
dw_scheme: -0.664479,0.398244,0.632352,3000
dw_scheme: -0.833786,0.12954,0.536674,3000
dw_scheme: 0.0153599,0.946591,0.32207,3000
dw_scheme: 0.277819,0.117274,0.953448,3000
dw_scheme: 0.573923,-0.374268,0.728379,3000
dw_scheme: 0.044931,-0.194184,0.979935,0
dw_scheme: 0.541768,-0.650292,0.532548,3000
dw_scheme: -0.535421,-0.844576,-0.00410061,3000
dw_scheme: -0.250473,0.0972285,0.963229,3000
dw_scheme: -0.404972,0.364535,0.838518,3000
dw_scheme: 0.30481,-0.573312,0.760529,3000
dw_scheme: 0.406421,0.849049,0.337547,3000
dw_scheme: 0.227779,-0.96846,-0.101004,3000
dw_scheme: 0.325817,-0.919378,0.220424,3000
dw_scheme: 0.933514,-0.159397,0.32116,3000
dw_scheme: 0.044931,-0.194184,0.979935,0
dw_scheme: 0.46804,0.636861,0.612655,3000
````

I am now checking whether https://github.com/MRtrix3/mrtrix3/commit/ad2c774f761f02b0d1cc70524dab39f670481316 may fix the issue. I'll be back later.

**Comment by chunhungyeh** [comment]
Hmm...I got the same outcome with https://github.com/MRtrix3/mrtrix3/commit/ad2c774f761f02b0d1cc70524dab39f670481316. It did not seem to fix the issue.

**Comment by Lestropie** [comment]
Just eyeballing, looks like a systematic rotation applied to all vectors.

If it's a concern, change the script to load the gradient table into the output file from the 'series.mif' file rather than bvecs / bvals.

Then to debug, run the script with the -nocleanup option, and experiment with the files in there. Eg. Regenerate bvecs / bvals to see if eddy had modified them, try comparing a dwgrad dump to a bvecs/bvals export - import - dwgrad dump to see if our conversion code is introducing a rotation.

**Comment by chunhungyeh** [comment]
I have changed the script to make the output data have the same gradient scheme as the input data. I think it would be better like this for now (if you agree) so that users who run this script may not obtain funny FOD results.

I will try finding out at which level the directions are rotated as suggested by @Lestropie.

**Comment by Lestropie** [comment]
Fixed by f28a45f3b97.
